### ISSUE TITLE
Updates need for gradle 2.4

### ISSUE THREAD

**Issue by sparkym3** [dcendents/android-maven-gradle-plugin#20]
The library needs to be updated to support gradle 2.4 which has an updated constructor signature for the DefaultDeployerFactory.

Here is the update in the MavenPlugin that can be copied
https://github.com/gradle/gradle/blob/master/subprojects/maven/src/main/groovy/org/gradle/api/plugins/MavenPlugin.java

**Comment by bbarnhill** [comment]
+1 this is causing our builds to fail with 2.3 ... going to be stuck with 2.2.1 till this gets fixed since 2.3 doesnt work.

**Comment by sparkym3** [comment]
Yes, it looks like this issue with the plugin does exist on 2.3, I skipped over that as we are having a separate issue on 2.3 that is fixed with 2.4 and prevents us from using it. That issue is https://issues.gradle.org/browse/GRADLE-3243

**Comment by sparkym3** [comment]
It looks like this app's build is using the gradle-plugindev-plugin which is dependent on gradle-bintray-pluugin which has the following is and does not currently support 2.4.

I have logged the following issues in both of those spaces to get them updated, but if you know of an alternative fix that could get this out quicker it would be appreciated.
https://github.com/etiennestuder/gradle-plugindev-plugin/issues/26
https://github.com/bintray/gradle-bintray-plugin/issues/70

**Comment by dcendents** [comment]
I have no issue with gradle 2.3, can you please share your config so I can have a look?

I will also prepare for gradle 2.4 to be ready when it comes out.

**Comment by dcendents** [comment]
Hi,

I've released version 1.3 of the plugin which is compatible with gradle 2.4: https://plugins.gradle.org/plugin/com.github.dcendents.android-maven

Also not that I have changed the artifact name which is now android-maven-gradle-plugin, but I have kept the same plugin id.

It It should get sync to jcenter and central soon, unless the new artifact id causes a problem.
