### ISSUE TITLE
Error: Unable to find method 'org.gradle.internal.project.ProjectInternal.getPluginManager()

### ISSUE THREAD

**Issue by doneill** [dcendents/android-maven-gradle-plugin#22]
I am getting this error when migrating to the new naming structure.  I have updated the following: 

```groovy
repositories {
    jcenter()
}

dependencies {
    classpath 'com.github.dcendents:android-maven-gradle-plugin:1.3'

// this was apply plugin android-maven
apply plugin: 'com.github.dcendents.android-maven'
}
```

**Comment by dcendents** [comment]
which version of gradle are you using?

if you use the version 1.3 of the plugin then you should be using gradle 2.4

**Comment by doneill** [comment]
Yep, I am using gradle 2.4

**Comment by doneill** [comment]
I am updating my android sdk now from 24.1.2 to 24.2.

**Comment by dcendents** [comment]
it looks more like a gradle error than the android sdk

in the code you pasted above, you apply the plugin within the dependencies block, is it a typo? otherwise that might be the problem.

**Comment by doneill** [comment]
Yes, that is a typo.  I resolved the issue by clearing the gradle cache completely.  Thanks for your attention to the issue.

**Comment by ppamorim** [comment]
+1

**Comment by cerberillo** [comment]
This safe me hours :+1:
