### ISSUE TITLE
Lack of packaging type when dependency is module

### ISSUE THREAD

**Issue by kkalisz** [dcendents/android-maven-gradle-plugin#24]
When I have mulitmodule project
-root:
--liba:aar
--libb:aar

liba has 'compile project' dependency to libb,

After uploadingArchives libb pom has dependency to liba with default packaging ( jar ).
I know when I use libb as dependency in gradle project everything will be fine because gradle has no problem with resolving packaging.
But we have  few maven projects which use this dependency and maven can't resolve artifact.

Is there any posibility to define packaging type when using 'compile project' dependency ??
Or maybe it should be done automaticaly !?

Thanks for help.

**Comment by dcendents** [comment]
This is something you will need to configure manually for each project. AFAIK, the gradle dependencies are introspected when building the pom but the type is always null for internal project dependencies so it defaults to jar.

You need to let the maven installer know the exact type you want for the aar dependencies, something like this:

```gradle
ext.mavenPomConfig = {
	pom.whenConfigured {pom ->
		pom.dependencies.find {dep -> dep.groupId == 'multiproject' && dep.artifactId == 'baseLibrary' }.type = 'aar'
	}
}

install.repositories.mavenInstaller mavenPomConfig
uploadArchives.repositories.mavenDeployer mavenPomConfig
```

Let me know if that works for you
