### ISSUE TITLE
Versions prior to 1.3 don't seem to be in jcenter()/mavencentral() anymore

### ISSUE THREAD

**Issue by loeschg** [dcendents/android-maven-gradle-plugin#25]
The documentation/README suggestions looking at the version of gradle being run and pick the appropriate plugin version. It looks like only 1.3 is available when I navigate to https://repo1.maven.org/maven2/com/github/dcendents/android-maven-gradle-plugin/.

Does the documentation need updated?

**Comment by dcendents** [comment]
Hi,

The project used to be called android-maven-plugin, but I renamed it after a request from developers of another project of the same name (plugin to do android development with maven).

You're right that the documentation is misleading, I'll update it.

You can find the previous versions here: https://repo1.maven.org/maven2/com/github/dcendents/android-maven-plugin/

Cheers,
Dan

**Comment by loeschg** [comment]
:+1: Thanks! Worked for me to just update to 2.4 :)

**Comment by AfzalivE** [comment]
Where is version 1.3 now? Can't find it on mavenCentral, in that link or jcenter.
