### ISSUE TITLE
How do I set the artifact ID? rootProject.name doesn't seem to work

### ISSUE THREAD

**Issue by loeschg** [dcendents/android-maven-gradle-plugin#26]
I have a "typical" module project where I have both "sample" and "plugin" directories. `sample` contains how to use the `plugin` module.

When setting rootProject.name="test-artifact-name" and run `gradle install` the generated artifact is the original name (as if the rootProject.name wasn't picked up). 

Any help would be great!

**Comment by dcendents** [comment]
rootProject.name only works with the root project in a multi-module build.

Please see my comment on issue #9 for different alternatives you can use to set the artifactId.

Let me know it that fixes the problem

**Comment by loeschg** [comment]
Thanks! I am using jitpack.io for the time being, and the name is pulled via the repository name, so it didn't end up mattering.
