### ISSUE TITLE
help configuring the install pom

### ISSUE THREAD

**Issue by ccoulton** [dcendents/android-maven-gradle-plugin#31]
So I'm having trouble configuring the pom that is installed w/ the the plugin  such that it works when i use the uploadArchieves task and i want the same pom file so i can test the library locally but also allow the build server to build and install the apk/arr in the git repo

i.e. I would like the same pom that goes out when I publish to MC to be created when i install locally
```groovy
uploadArchives{
	repositories{
		mavenDeployer {...
			pom.project {...
                        }
		}
	}
}

install{
	repositories.mavenLocal().url = "file:/"+configFile.absolutePath
}
```

**Comment by dcendents** [comment]
Both the uploadArchives and the install tasks support pom customisation.
See section 31.6.4: https://docs.gradle.org/current/userguide/maven_plugin.html


This worked for me and produced 2 identically pom files:

```gradle
ext.mavenPomConfig = {
	pom.whenConfigured {pom ->
		pom.artifactId = 'myMavenName'
		pom.dependencies.find {dep -> dep.groupId == 'multiproject' && dep.artifactId == 'baseLibrary' }.type = 'aar'
		pom.project {
			licenses {
				license {
					name 'The Apache Software License, Version 2.0'
					url 'http://www.apache.org/licenses/LICENSE-2.0.txt'
					distribution 'repo'
				}
			}
		}
	}
}

install.repositories.mavenInstaller mavenPomConfig
uploadArchives.repositories.mavenDeployer mavenPomConfig

// this is simply to test I upload the file locally
uploadArchives {
    repositories {
        mavenDeployer {
            repository(url: "file://C:/tmp/myRepo/")
        }
    }
}
```

**Comment by ccoulton** [comment]
the install task is saying it could not publish configuration 'archives'

thanks for the help, I'm trying to offer installing the maven not to .m2 but to the local. the uploadArchives tasks works when i try and push it locally, the install task doesn't want to create the pom, most likely an Issue w/ my config.

**Comment by ccoulton** [comment]
So sorry I got it figured out, just basicly had it depend on uploadArchives, and changed where it pointed and called upload archives again. sorry for bothering you have a good day closing issue.

**Comment by ccoulton** [comment]
Ok so like before I've made a hack to deal with the pom file, Simply had to copy and rename the pom to fit the format. But install doesn't create the jar that uploadArchives does.  Other than using a snapshot repo or somthing like that to use the same type of publishing uploadArchives to a local repo so I don't have to push to a remote when doing local testing.

**Comment by ccoulton** [comment]
Ok so like before I've made a hack to deal with the pom file, Simply had to copy and rename the pom to fit the format. But install doesn't create the jar that uploadArchives does.  Other than using a snapshot repo or somthing like that to use the same type of publishing uploadArchives to a local repo so I don't have to push to a remote when doing local testing.
