### ISSUE TITLE
Incompatible with gradle 2.14

### ISSUE THREAD

**Issue by amitav13** [dcendents/android-maven-gradle-plugin#33]
Gradle 2.14 released today and has made some breaking changes. This plugin is probably affected by this one - "Gradle implementation dependencies are not visible to plugins at development time".

[Release notes](https://docs.gradle.org/current/release-notes)

The error that I'm seeing is:

>Error:(2, 1) A problem occurred evaluating project ':presentation'.
> Failed to apply plugin [id 'com.github.dcendents.android-maven']
> Could not create plugin of type 'AndroidMavenPlugin'.

**Comment by dcendents** [comment]
Hi, I'm currently away on paternity leave but I'll update it as soon as I can, hopefully just a few days

**Comment by amitav13** [comment]
Sure, no problem. Congratulations!

**Comment by sparkym3** [comment]
I have created a pull to resolve this issue. It is a breaking change with all previous versions of gradle.
https://github.com/dcendents/android-maven-gradle-plugin/pull/34

**Comment by dcendents** [comment]
I have released version 1.4 to be used with gradle 2.14

Please let me know if you have any issues with it.

Regards

**Comment by europa** [comment]
@amitav13 how to solve this problem?

**Comment by dcendents** [comment]
@europa simply update android-maven-gradle-plugin to version 1.4.1

**Comment by abhinavrathore019-gh** [comment]
I had the same issue:

the combination of the following versions is working for me:

inside **project level gradle** 
```
classpath 'com.android.tools.build:gradle:2.3.0+'
classpath 'com.jfrog.bintray.gradle:gradle-bintray-plugin:1.0'
classpath 'com.github.dcendents:android-maven-gradle-plugin:1.4.1'
```

and in **gradle-wrapper.properties**
`distributionUrl=https\://services.gradle.org/distributions/gradle-3.3-all.zip`
