### ISSUE TITLE
Issue with android-maven-gradle-plugin 1.4

### ISSUE THREAD

**Issue by vivekkiran** [dcendents/android-maven-gradle-plugin#35]
> (class: org/apache/maven/project/MavenProject, method: getSnapshotArtifactRepository signature: ()Lorg/apache/maven/artifact/repository/ArtifactRepository;) Incompatible argument to function

**Comment by dcendents** [comment]
Is your project public?
If so can you give me the link?

Otherwise please give me more information about your configuration.
And make sure you are using gradle 2.14

**Comment by vivekkiran** [comment]
Yes, its public https://github.com/nbostech/wavelabs-android-client-api

**Comment by dcendents** [comment]
I'll have a look tonight (EDT timezone)

**Comment by dcendents** [comment]
Everything works for me

did a clone of your project on the master branch

```bash
./gradlew clean build install --info
```

The aar library is correctly installed in my local m2 repository

**Comment by gyulavoros** [comment]
I have the same issue but not with `gradle install` (that works fine), rather than `gradle bintrayUpload`. The project setup is roughly like [this](https://github.com/bintray/bintray-examples/tree/master/gradle-bintray-plugin-examples/android-maven-example) example, but with the latest versions:
- Gradle 2.14
- android-maven-gradle-plugin 1.4
- com.jfrog.bintray 1.7

**Comment by hbsis-lucianorodrigues** [comment]
I've the same problem

**Comment by TakWolf** [comment]
I've the same problem.

**Comment by dcendents** [comment]
Thanks @gyulavoros I managed to reproduce the problem with the project you linked. 

With the latest gradle version I need to add a dependency to maven-core and although I used the same version that gradle specified, I guess the bintray plugin used a different one.

Anyway I modified the dependency to compileOnly so it is ignored in the pom and it fixes the problem.

I've released version 1.4.1, give it some time to sync to all the repos and give it a go.

Cheers

**Comment by TakWolf** [comment]
@dcendents 
It works with 1.4.1, thanks for your contribution !!

**Comment by gyulavoros** [comment]
@dcendents Perfect, thank you!

**Comment by servletabc** [comment]
thank you
