### ISSUE TITLE
deploy aar to remote repo

### ISSUE THREAD

**Issue by dingzhihu** [dcendents/android-maven-gradle-plugin#4]
This is a great plugin, but how to deploy aar to remote repo(like maven central repo) using this plugin? many thanks

**Comment by thuytrinh** [comment]
@dcendents So ```uploadArchives``` will do the same thing as ```install```, right? (apart from deploying to a custom repo).

**Comment by dcendents** [comment]
Yes, it will deploy all of the project's archives.
