### ISSUE TITLE
Could not create plugin type 'AndroidMavenPlugin'

### ISSUE THREAD

**Issue by janechung** [dcendents/android-maven-gradle-plugin#44]
We are getting this error message when trying to upload to bintray: 

A problem occurred evaluating project ':project_name'.
> Failed to apply plugin [id 'com.github.dcendents.android-maven']
   > Could not create plugin of type 'AndroidMavenPlugin'.

We're using gradle version 2.4 with plugin version 1.3. An upload two days ago was successful.

**Comment by neversad-dev** [comment]
same problem. Could you help?

**Comment by dcendents** [comment]
Unless I can debug your build there isn't much I can do. 
Is the project public?

If not can you post your build.gradle?

**Comment by neversad-dev** [comment]
https://github.com/GiveNoCode/Useful-Stuff-Android

**Comment by dcendents** [comment]
You are not using the correct version of the plugin.

As per the documentation (https://github.com/dcendents/android-maven-gradle-plugin#note-on-releases), when using gradle 2.14.1 you need to use the plugin version 1.4.1.
