### ISSUE TITLE
1.4.+ generates jar file as well as AAR

### ISSUE THREAD

**Issue by ansman** [dcendents/android-maven-gradle-plugin#45]
When using 1.3 only AAR files were generated when building but now a jar file is generated too which requires us to suffix the dependency with `@aar`. Not a huge issue but still annoying, is there any way to disable the jar file generation?

**Comment by dcendents** [comment]
I cannot reproduce this behavior.

Is your project public or otherwise can you post your build.gradle?

**Comment by ansman** [comment]
I can't reproduce it now either, my bad.
