### ISSUE TITLE
How can I assign my module's artifactId

### ISSUE THREAD

**Issue by huhuang03** [dcendents/android-maven-gradle-plugin#47]
For example 
I have a project foo which have a module named bar

foo
---bar(android lib)
---app

And I want upload my bar arr, with artifactId name aBar. By default it use my bar's name which is bar
How can I config this
Thanks!

**Comment by huhuang03** [comment]
I just find it's same as the closed issue 
https://github.com/dcendents/android-maven-gradle-plugin/issues/9

And 
`roject.archivesBaseName = 'archive-name'`
solved my problem.

How can I close this issue...

**Comment by codeangi** [comment]
Templates

**Comment by codeangi** [comment]
Templates
