### ISSUE TITLE
Gradle 4.6 fails

### ISSUE THREAD

**Issue by axet** [dcendents/android-maven-gradle-plugin#66]
Hello!

Recent gradle fails with android gradle 2.0 plugin:

```
* What went wrong:
org.gradle.api.internal.artifacts.ivyservice.projectmodule.DefaultProjectPublication.<init>(Lorg/gradle/api/artifacts/ModuleVersionIdentifier;)V

java.lang.NoSuchMethodError: org.gradle.api.internal.artifacts.ivyservice.projectmodule.DefaultProjectPublication.<init>(Lorg/gradle/api/artifacts/ModuleVersionIdentifier;)V
        at org.gradle.api.plugins.AndroidMavenPlugin$9.execute(AndroidMavenPlugin.java:184)
        at org.gradle.api.plugins.AndroidMavenPlugin$9.execute(AndroidMavenPlugin.java:168)
        at org.gradle.configuration.project.DelayedConfigurationActions.execute(DelayedConfigurationActions.java:27)

```

**Comment by dcendents** [comment]
I have release version 2.1 that should fix the problem. Please update your project to use it.

**Comment by axet** [comment]
Thanks! Android library is rescued!

**Comment by axet** [comment]
@dcendents 'gradle install' does work, but Android Studio 3.1 failed to compile projects with 2.1 with following error:

```
Unable to find method 'org.gradle.internal.Describables.withTypeAndName(Ljava/lang/String;Ljava/lang/String;)Lorg/gradle/internal/DisplayName;'.
```

**Comment by Sinapse87** [comment]
Same for me. Can you help?

**Comment by xiaobailong24** [comment]
@axet @Sinapse87 
Pls read README.md
![image](https://user-images.githubusercontent.com/9431974/43944123-750364a0-9cb0-11e8-9068-232e290b59bf.png)

**Comment by IgorGanapolsky** [comment]
I am getting the same error.  Is there a resolution?

**Comment by manishcybernext** [comment]
tried to access method org.gradle.api.internal.artifacts.DefaultModuleVersionIdentifier.<init>(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V from class org.gradle.api.plugins.AndroidMavenPlugin$8

same issue. please help
