### ISSUE TITLE
Getting this error: "Declaring custom 'clean' task when using the standard Gradle lifecycle plugins is not allowed." when using the plugin {} block

### ISSUE THREAD

**Issue by Muddz** [dcendents/android-maven-gradle-plugin#75]
When I use this plugin block in my `build.gradle` (project level) I get the error `Declaring custom 'clean' task when using the standard Gradle lifecycle plugins is not allowed` on gradle sync

    plugins {
    id "com.github.dcendents.android-maven" version "2.1"
    }

But when adding the plugin via the old way in the `dependencies{}` block it won't complain about the `task clean(){}`

How do I handle this? It only does it with this plugin. 

    buildscript {

    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.2.0'
        classpath "com.jfrog.bintray.gradle:gradle-bintray-plugin:1.8.4"  This works when used here
     }
    }

        plugins {
    id "com.github.dcendents.android-maven" version "2.1" //This dont work here. Gradle complains about "clean task"
    id "com.jfrog.bintray" version "1.8.4" 
    }

    allprojects {
    repositories {
        google()
        jcenter()
    }
    }

    //This was here by default 
    task clean(type: Delete) {
    delete rootProject.buildDir
    }

**Comment by richardavinash12** [comment]
Hi @Muddz , Did you fix this issue? I am also facing the same issue.

**Comment by Muddz** [comment]
@richardavinash12 No I haven't touched it since and the developer of the library has stopped the support of it
